### ISSUE TITLE
SUBTLETY - html entities

### ISSUE THREAD

**Issue by franfranfranfran** [PerKaae/prj-rev-bwfs-dasmoto#2]
https://github.com/PerKaae/prj-rev-bwfs-dasmoto/blob/master/Dashmoto/index.html#L11

consider using an html entity to represent the & special character to ensure that the character displays correctly across all browsers. more info can be found here - https://www.w3schools.com/html/html_entities.asp

**Comment by PerKaae** [comment]
Understood, I've implemented this in my local folder.
