### ISSUE TITLE
IMPORTANT - img alt attribute

### ISSUE THREAD

**Issue by franfranfranfran** [PerKaae/prj-rev-bwfs-dasmoto#4]
https://github.com/PerKaae/prj-rev-bwfs-dasmoto/blob/master/Dashmoto/index.html#L16
etc...

make sure to use an alt attribute for each img element to ensure that a wider variety of users have access to the information contained in those images. more info can be found here - https://www.w3schools.com/tags/att_img_alt.asp

**Comment by PerKaae** [comment]
Understood, I've implemented this in my local folder.
