### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [PerKaae/prj-rev-bwfs-dasmoto#5]
**GRADE**: Meets Expectations

**SUMMARY**: Good work on this project. The site itself looks great and you did an excellent job keeping the project folder and the code neat, organized, and readable. Nice job using divs and classes to structure and label the content on the page as well.

Behind the scenes in the html, make sure to use the alt attribute on your img elements to ensure that a wider variety of users have access to the information being presented in them. Also, consider using html entities to represent special characters on the page to make sure that they display correctly no matter where they are being viewed.

As a next step try saving your image files locally to an images folder inside of resources and then using relative file paths to link to those from your html and css. The link to css on line 5 of your html is a great example and more info can be found here - http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/

Keep up the good work!

**Comment by PerKaae** [comment]
Thanks for the feedback. I've implemented everything in my local html and css files. However I do have a problem when I try to make a relative file path from my css file. I've tried to use this: background-image: url("./resources/images/pattern.jpeg"). The image won't show unless I link to a website. It works fine with the relative paths from the html file. What do I do wrong?

**Comment by PerKaae** [comment]
I got it now :-) I realize that the css file was not located in the root. I used this command to solve it: background-image: url("../images/pattern.jpeg")
